#!/bin/bash

if [[ $# -gt 1 ]] && [[ $1 == -- ]]; then
  shift
elif [[ $# -eq 0 ]] || [[ $1 == -* ]]; then
  echo "Usage: ${0##*/} [--] FILE..." >&2
  exit 64
fi

let ERRORS=0
for PROGRAM in "$@"; do
  LIBRARIES=$(/lib/ld.so --list "$PROGRAM")
  if [[ -n $LIBRARIES ]]; then
    printf '%s:\n%s\n' "$PROGRAM" "$LIBRARIES"
  else
    let ERRORS=1
  fi
done
exit $ERRORS
