#!/bin/bash -e

if [[ $UID -eq 0 ]]; then
  mkdir -m 0700 -p /var/lib/uschedule
  cd /var/lib/uschedule
else
  mkdir -m 0700 -p "$HOME/.uschedule"
  cd "$HOME/.uschedule"
fi

mkdir -p commands
[[ -p fifo ]] || mkfifo fifo
